### ISSUE TITLE
Staged VCF deployment

### ISSUE THREAD

**Issue by pikolos** [Tanzu-Solutions-Engineering/cPodFactory#7]
Have a flexible approach for building VCF deployments with individual scripts that can be customised depending on the demo needs in a solution file. 

Stages:

1. Deploy Cloud builder
2. add_host (done in issue-4)
3. Deploy MGMT
4. Commission host (input $hosts)
5. Add Workload domain with NSX (input $hosts)
7. Add cluster (input $hosts)

Future stages not included in this feature:
1. Add new Workload domain with shared NSX (input $hosts)
2. Create stretched cluster 
3. Reuse shared cloudbuilder
4. Deploy modified MGMT (single host, single NSX mgr)
5. Create WLD in new cPOD (simulate remote clusters)

**Comment by vEDW** [comment]
let's discuss how to address this.
there are already elements available, like below. These need finalising though.
https://github.com/Tanzu-Solutions-Engineering/cPodFactory/blob/dom-cobb/compute/generate_cloudbuilder.sh
https://github.com/Tanzu-Solutions-Engineering/cPodFactory/blob/dom-cobb/compute/generate_sddc_vi.sh
